/**
 * 
 */
package br.ufu.facom.lsi.prefrec.crossvalidation;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.util.List;
import java.util.Map;

import br.ufu.facom.lsi.prefrec.representation.model.StratifiedMatrix;

/**
 * @author Klerisson
 *
 */
public class CrossValidation {

	private StratifiedMatrix sm;

	/**
	 * Read the Stratified Matrices, by item and by user, inputs generated by
	 * prefrec Stratification module
	 */
	public void readInput() throws Exception {

		try (InputStream file = new FileInputStream(new File(
				"../StratifiedMatrixByUser.prefrecstratificator"));
				InputStream buffer = new BufferedInputStream(file);
				ObjectInput input = new ObjectInputStream(buffer);) {

			// deserialize the Map
			this.sm = (StratifiedMatrix) input.readObject();

		} catch (Exception e) {
			throw e;
		}

	}

}
